<?php

namespace HnhDigital\SlackApi;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Dnd class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Dnd extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Retrieves a user's current Do Not Disturb status.
     *
     * @link https://api.slack.com/methods/dnd.info
     *
     * @return array
     */
    public function info($optional = [])
    {
        return $this->apiCall('get', '/dnd.info');
    }

    /**
     * Retrieves the Do Not Disturb status for users on a team.
     *
     * @link https://api.slack.com/methods/dnd.teamInfo
     *
     * @return array
     */
    public function teamInfo($optional = [])
    {
        return $this->apiCall('get', '/dnd.teamInfo');
    }

    /**
     * Ends the current user's Do Not Disturb session immediately.
     *
     * @link https://api.slack.com/methods/dnd.endDnd
     *
     * @return mixed
     */
    public function endDnd()
    {
        return $this->apiCall('post', '/dnd.endDnd');
    }

    /**
     * Ends the current user's snooze mode immediately.
     *
     * @link https://api.slack.com/methods/dnd.endSnooze
     *
     * @return mixed
     */
    public function endSnooze()
    {
        return $this->apiCall('post', '/dnd.endSnooze');
    }

    /**
     * Turns on Do Not Disturb mode for the current user, or changes its duration.
     *
     * @param array $optional
     *                        - [num_minutes=null] (integer) Number of minutes, from now, to snooze until.
     *
     * @link https://api.slack.com/methods/dnd.setSnooze
     *
     * @return mixed
     */
    public function setSnooze($optional = [])
    {
        return $this->apiCall('post', '/dnd.setSnooze', ['json' => array_merge([
        ], $optional)]);
    }
}
