<?php

namespace HnhDigital\SlackApi;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Im class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Im extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Fetches history of messages and events from direct message channel.
     *
     * @link https://api.slack.com/methods/im.history
     *
     * @return array
     */
    public function history($optional = [])
    {
        return $this->apiCall('get', '/im.history');
    }

    /**
     * Lists direct message channels for the calling user.
     *
     * @link https://api.slack.com/methods/im.list
     *
     * @return array
     */
    public function getList($optional = [])
    {
        return $this->apiCall('get', '/im.list');
    }

    /**
     * Retrieve a thread of messages posted to a direct message conversation
     *
     * @link https://api.slack.com/methods/im.replies
     *
     * @return array
     */
    public function replies($optional = [])
    {
        return $this->apiCall('get', '/im.replies');
    }

    /**
     * Close a direct message channel.
     *
     * @param array $optional
     *                        - [channel=null] (string) Direct message channel to close.
     *
     * @link https://api.slack.com/methods/im.close
     *
     * @return mixed
     */
    public function close($optional = [])
    {
        return $this->apiCall('post', '/im.close', ['json' => array_merge([
        ], $optional)]);
    }

    /**
     * Sets the read cursor in a direct message channel.
     *
     * @param array $optional
     *                        - [ts=null] (number) Timestamp of the most recently seen message.
     *                        - [channel=null] (string) Direct message channel to set reading cursor in.
     *
     * @link https://api.slack.com/methods/im.mark
     *
     * @return mixed
     */
    public function mark($optional = [])
    {
        return $this->apiCall('post', '/im.mark', ['json' => array_merge([
        ], $optional)]);
    }

    /**
     * Opens a direct message channel.
     *
     * @param array $optional
     *                        - [return_im=null] (boolean) Boolean, indicates you want the full IM channel
     *                        definition in the response.
     *                        - [user=null] (string) User to open a direct message channel with.
     *                        - [include_locale=null] (boolean) Set this to `true` to receive the locale for this im.
     *                        Defaults to `false`
     *
     * @link https://api.slack.com/methods/im.open
     *
     * @return mixed
     */
    public function open($optional = [])
    {
        return $this->apiCall('post', '/im.open', ['json' => array_merge([
        ], $optional)]);
    }
}
