<?php

namespace HnhDigital\SlackApi;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Oauth class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Oauth extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Exchanges a temporary OAuth verifier code for an access token.
     *
     * @link https://api.slack.com/methods/oauth.access
     *
     * @return array
     */
    public function access($optional = [])
    {
        return $this->apiCall('get', '/oauth.access');
    }

    /**
     * Exchanges a temporary OAuth verifier code for a workspace token.
     *
     * @link https://api.slack.com/methods/oauth.token
     *
     * @return array
     */
    public function token($optional = [])
    {
        return $this->apiCall('get', '/oauth.token');
    }
}
