<?php

namespace HnhDigital\SlackApi;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Pins class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Pins extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Lists items pinned to a channel.
     *
     * @link https://api.slack.com/methods/pins.list
     *
     * @return array
     */
    public function getList($optional = [])
    {
        return $this->apiCall('get', '/pins.list');
    }

    /**
     * Pins an item to a channel.
     *
     * @param array $optional
     *                        - [file_comment=null] (string) File comment to pin.
     *                        - [timestamp=null] (number) Timestamp of the message to pin.
     *                        - [file=null] (string) File to pin.
     *                        - [channel=null] (string) Channel to pin the item in.
     *
     * @link https://api.slack.com/methods/pins.add
     *
     * @return mixed
     */
    public function add($optional = [])
    {
        return $this->apiCall('post', '/pins.add', ['json' => array_merge([
        ], $optional)]);
    }

    /**
     * Un-pins an item from a channel.
     *
     * @param array $optional
     *                        - [file_comment=null] (string) File comment to un-pin.
     *                        - [timestamp=null] (number) Timestamp of the message to un-pin.
     *                        - [file=null] (string) File to un-pin.
     *                        - [channel=null] (string) Channel where the item is pinned to.
     *
     * @link https://api.slack.com/methods/pins.remove
     *
     * @return mixed
     */
    public function remove($optional = [])
    {
        return $this->apiCall('post', '/pins.remove', ['json' => array_merge([
        ], $optional)]);
    }
}
