<?php

namespace HnhDigital\SlackApi;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Reactions class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Reactions extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Gets reactions for an item.
     *
     * @link https://api.slack.com/methods/reactions.get
     *
     * @return array
     */
    public function get($optional = [])
    {
        return $this->apiCall('get', '/reactions.get');
    }

    /**
     * Lists reactions made by a user.
     *
     * @link https://api.slack.com/methods/reactions.list
     *
     * @return array
     */
    public function getList($optional = [])
    {
        return $this->apiCall('get', '/reactions.list');
    }

    /**
     * Adds a reaction to an item.
     *
     * @param array $optional
     *                        - [name=null] (string) Reaction (emoji) name.
     *                        - [file_comment=null] (string) File comment to add reaction to.
     *                        - [timestamp=null] (number) Timestamp of the message to add reaction to.
     *                        - [file=null] (string) File to add reaction to.
     *                        - [channel=null] (string) Channel where the message to add reaction to was posted.
     *
     * @link https://api.slack.com/methods/reactions.add
     *
     * @return mixed
     */
    public function add($optional = [])
    {
        return $this->apiCall('post', '/reactions.add', ['json' => array_merge([
        ], $optional)]);
    }

    /**
     * Removes a reaction from an item.
     *
     * @param array $optional
     *                        - [name=null] (string) Reaction (emoji) name.
     *                        - [file_comment=null] (string) File comment to remove reaction from.
     *                        - [timestamp=null] (number) Timestamp of the message to remove reaction from.
     *                        - [file=null] (string) File to remove reaction from.
     *                        - [channel=null] (string) Channel where the message to remove reaction from was
     *                        posted.
     *
     * @link https://api.slack.com/methods/reactions.remove
     *
     * @return mixed
     */
    public function remove($optional = [])
    {
        return $this->apiCall('post', '/reactions.remove', ['json' => array_merge([
        ], $optional)]);
    }
}
