<?php

namespace HnhDigital\SlackApi;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Search class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Search extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Searches for messages and files matching a query.
     *
     * @link https://api.slack.com/methods/search.all
     *
     * @return array
     */
    public function all($optional = [])
    {
        return $this->apiCall('get', '/search.all');
    }

    /**
     * Searches for files matching a query.
     *
     * @link https://api.slack.com/methods/search.files
     *
     * @return array
     */
    public function files($optional = [])
    {
        return $this->apiCall('get', '/search.files');
    }

    /**
     * Searches for messages matching a query.
     *
     * @link https://api.slack.com/methods/search.messages
     *
     * @return array
     */
    public function messages($optional = [])
    {
        return $this->apiCall('get', '/search.messages');
    }
}
