<?php

namespace HnhDigital\SlackApi;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Stars class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Stars extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Lists stars for a user.
     *
     * @link https://api.slack.com/methods/stars.list
     *
     * @return array
     */
    public function getList($optional = [])
    {
        return $this->apiCall('get', '/stars.list');
    }

    /**
     * Adds a star to an item.
     *
     * @param array $optional
     *                        - [file_comment=null] (string) File comment to add star to.
     *                        - [timestamp=null] (number) Timestamp of the message to add star to.
     *                        - [channel=null] (string) Channel to add star to, or channel where the message to
     *                        add star to was posted (used with `timestamp`).
     *                        - [file=null] (string) File to add star to.
     *
     * @link https://api.slack.com/methods/stars.add
     *
     * @return mixed
     */
    public function add($optional = [])
    {
        return $this->apiCall('post', '/stars.add', ['json' => array_merge([
        ], $optional)]);
    }

    /**
     * Removes a star from an item.
     *
     * @param array $optional
     *                        - [file_comment=null] (string) File comment to remove star from.
     *                        - [timestamp=null] (number) Timestamp of the message to remove star from.
     *                        - [channel=null] (string) Channel to remove star from, or channel where the
     *                        message to remove star from was posted (used with
     *                        `timestamp`).
     *                        - [file=null] (string) File to remove star from.
     *
     * @link https://api.slack.com/methods/stars.remove
     *
     * @return mixed
     */
    public function remove($optional = [])
    {
        return $this->apiCall('post', '/stars.remove', ['json' => array_merge([
        ], $optional)]);
    }
}
