<?php

namespace HnhDigital\SlackApi\Files;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Comments class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Comments extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Add a comment to an existing file.
     *
     * @param array $optional
     *                        - [comment=null] (string) Text of the comment to add.
     *                        - [file=null] (string) File to add a comment to.
     *
     * @link https://api.slack.com/methods/files.comments.add
     *
     * @return mixed
     */
    public function add($optional = [])
    {
        return $this->apiCall('post', '/files.comments.add', ['json' => array_merge([
        ], $optional)]);
    }

    /**
     * Deletes an existing comment on a file.
     *
     * @param array $optional
     *                        - [id=null] (string) The comment to delete.
     *                        - [file=null] (string) File to delete a comment from.
     *
     * @link https://api.slack.com/methods/files.comments.delete
     *
     * @return mixed
     */
    public function delete($optional = [])
    {
        return $this->apiCall('post', '/files.comments.delete', ['json' => array_merge([
        ], $optional)]);
    }

    /**
     * Edit an existing file comment.
     *
     * @param array $optional
     *                        - [comment=null] (string) Text of the comment to edit.
     *                        - [id=null] (string) The comment to edit.
     *                        - [file=null] (string) File containing the comment to edit.
     *
     * @link https://api.slack.com/methods/files.comments.edit
     *
     * @return mixed
     */
    public function edit($optional = [])
    {
        return $this->apiCall('post', '/files.comments.edit', ['json' => array_merge([
        ], $optional)]);
    }
}
