<?php

namespace HnhDigital\SlackApi\Apps\Permissions;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Scopes class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Scopes extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Returns list of scopes this app has on a team.
     *
     * @link https://api.slack.com/methods/apps.permissions.scopes.list
     *
     * @return array
     */
    public function getList()
    {
        return $this->apiCall('get', '/apps.permissions.scopes.list');
    }
}
