<?php

namespace HnhDigital\SlackApi\Apps;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Permissions class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Permissions extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Returns list of permissions this app has on a team.
     *
     * @link https://api.slack.com/methods/apps.permissions.info
     *
     * @return array
     */
    public function info()
    {
        return $this->apiCall('get', '/apps.permissions.info');
    }

    /**
     * Allows an app to request additional scopes
     *
     * @link https://api.slack.com/methods/apps.permissions.request
     *
     * @return array
     */
    public function request($optional = [])
    {
        return $this->apiCall('get', '/apps.permissions.request');
    }
}
