<?php

namespace HnhDigital\SlackApi\UserGroups;

/*
 * This file is part of the PHP Slack API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\SlackApi\Foundation\Base;

/**
 * This is the Users class.
 *
 * This file is automatically generated.
 *
 * @link 
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Users extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * List all users in a User Group
     *
     * @link https://api.slack.com/methods/usergroups.users.list
     *
     * @return array
     */
    public function getList($optional = [])
    {
        return $this->apiCall('get', '/usergroups.users.list');
    }

    /**
     * Update the list of users for a User Group
     *
     * @param array $optional
     *                        - [include_count=null] (boolean) Include the number of users in the User Group.
     *                        - [users=null] (string) A comma separated string of encoded user IDs that
     *                        represent the entire list of users for the User Group.
     *                        - [usergroup=null] (string) The encoded ID of the User Group to update.
     *
     * @link https://api.slack.com/methods/usergroups.users.update
     *
     * @return mixed
     */
    public function update($optional = [])
    {
        return $this->apiCall('post', '/usergroups.users.update', ['json' => array_merge([
        ], $optional)]);
    }
}
